# -*- coding: utf-8 -*-
"""Week 2 Python Task.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r6YQ_rf1vT3kGg8uRYGEdZqri2ZRgAOH

**Sum of elements in an array**
"""

# Create an array of both odd and even numbers
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Find the sum of its elements
sum_arr = 0
for num in arr:
    sum_arr += num

# Print the sum of the array's elements
print(f"The sum of the elements in the array is: {sum_arr}")